<?php

namespace Database\Seeders;

use App\Models\Account;
use Illuminate\Database\Seeder;

class AccountSeeder extends Seeder
{
    /**
     * Norwegian Standard Chart of Accounts (NS 4102) for AS companies.
     */
    public function run(): void
    {
        $accounts = [
            // Klasse 1 - Eiendeler (Assets)
            ['account_number' => '1000', 'name' => 'Forskning og utvikling', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1020', 'name' => 'Konsesjoner', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1030', 'name' => 'Patenter', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1040', 'name' => 'Lisenser', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1050', 'name' => 'Varemerker', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1070', 'name' => 'Utsatt skattefordel', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1080', 'name' => 'Goodwill', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1100', 'name' => 'Bygninger', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1120', 'name' => 'Bygningsmessige anlegg', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1130', 'name' => 'Anlegg under utførelse', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1200', 'name' => 'Maskiner og anlegg', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1220', 'name' => 'Verktøy og utstyr', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1230', 'name' => 'Inventar', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1240', 'name' => 'Kontormaskiner', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1250', 'name' => 'IT-utstyr', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1280', 'name' => 'Biler', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1300', 'name' => 'Investeringer i datterselskap', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1320', 'name' => 'Lån til foretak i samme konsern', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1340', 'name' => 'Investeringer i tilknyttet selskap', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1350', 'name' => 'Lån til tilknyttet selskap', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1360', 'name' => 'Investeringer i aksjer og andeler', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1370', 'name' => 'Obligasjoner', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1380', 'name' => 'Andre langsiktige fordringer', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1400', 'name' => 'Råvarer', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1420', 'name' => 'Varer under tilvirkning', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1440', 'name' => 'Ferdigvarer', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1460', 'name' => 'Innkjøpte varer for videresalg', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1500', 'name' => 'Kundefordringer', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1530', 'name' => 'Opptjent, ikke fakturert driftsinntekt', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1560', 'name' => 'Andre kortsiktige fordringer', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1570', 'name' => 'Fordringer på eiere', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1580', 'name' => 'Krav på innbetaling av selskapskapital', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1700', 'name' => 'Forskuddsbetalt leie', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1710', 'name' => 'Forskuddsbetalt forsikring', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1750', 'name' => 'Påløpte inntekter', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1800', 'name' => 'Aksjer og andeler', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1810', 'name' => 'Markedsbaserte aksjer', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1820', 'name' => 'Markedsbaserte obligasjoner', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1830', 'name' => 'Markedsbaserte sertifikater', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1900', 'name' => 'Kontanter', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1910', 'name' => 'Kasse', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1920', 'name' => 'Bank', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],
            ['account_number' => '1930', 'name' => 'Skattetrekkskonto', 'account_class' => '1', 'account_type' => 'asset', 'is_system' => true],

            // Klasse 2 - Egenkapital og gjeld (Equity & Liabilities)
            ['account_number' => '2000', 'name' => 'Aksjekapital', 'account_class' => '2', 'account_type' => 'equity', 'is_system' => true],
            ['account_number' => '2020', 'name' => 'Egne aksjer', 'account_class' => '2', 'account_type' => 'equity', 'is_system' => true],
            ['account_number' => '2030', 'name' => 'Overkursfond', 'account_class' => '2', 'account_type' => 'equity', 'is_system' => true],
            ['account_number' => '2050', 'name' => 'Annen innskutt egenkapital', 'account_class' => '2', 'account_type' => 'equity', 'is_system' => true],
            ['account_number' => '2080', 'name' => 'Udekket tap', 'account_class' => '2', 'account_type' => 'equity', 'is_system' => true],
            ['account_number' => '2090', 'name' => 'Annen egenkapital', 'account_class' => '2', 'account_type' => 'equity', 'is_system' => true],
            ['account_number' => '2100', 'name' => 'Fond for vurderingsforskjeller', 'account_class' => '2', 'account_type' => 'equity', 'is_system' => true],
            ['account_number' => '2120', 'name' => 'Fond for urealiserte gevinster', 'account_class' => '2', 'account_type' => 'equity', 'is_system' => true],
            ['account_number' => '2200', 'name' => 'Konvertible lån', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],
            ['account_number' => '2210', 'name' => 'Obligasjonslån', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],
            ['account_number' => '2220', 'name' => 'Gjeld til kredittinstitusjoner', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],
            ['account_number' => '2230', 'name' => 'Pantelån', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],
            ['account_number' => '2250', 'name' => 'Ansvarlig lån', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],
            ['account_number' => '2260', 'name' => 'Andre langsiktige lån', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],
            ['account_number' => '2280', 'name' => 'Utsatt skatt', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],
            ['account_number' => '2300', 'name' => 'Lån fra kredittinstitusjoner', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],
            ['account_number' => '2320', 'name' => 'Sertifikatlån', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],
            ['account_number' => '2340', 'name' => 'Byggelån', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],
            ['account_number' => '2350', 'name' => 'Gjeld til ansatte', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],
            ['account_number' => '2380', 'name' => 'Kassekreditt', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],
            ['account_number' => '2400', 'name' => 'Leverandørgjeld', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],
            ['account_number' => '2500', 'name' => 'Betalbar skatt', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],
            ['account_number' => '2600', 'name' => 'Skattetrekk', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],
            ['account_number' => '2610', 'name' => 'Påleggstrekk', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],
            ['account_number' => '2620', 'name' => 'Trygdetrekk', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],
            ['account_number' => '2630', 'name' => 'Bidragstrekk', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],
            ['account_number' => '2640', 'name' => 'Forsikringstrekk', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],
            ['account_number' => '2650', 'name' => 'Fagforeningstrekk', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],
            ['account_number' => '2700', 'name' => 'Utgående merverdiavgift', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true, 'vat_code' => '3'],
            ['account_number' => '2710', 'name' => 'Inngående merverdiavgift', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true, 'vat_code' => '1'],
            ['account_number' => '2720', 'name' => 'Inngående merverdiavgift, høy sats', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],
            ['account_number' => '2730', 'name' => 'Inngående merverdiavgift, middels sats', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],
            ['account_number' => '2740', 'name' => 'Inngående merverdiavgift, lav sats', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],
            ['account_number' => '2750', 'name' => 'Oppgjørskonto merverdiavgift', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],
            ['account_number' => '2760', 'name' => 'Investeringsavgift', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],
            ['account_number' => '2770', 'name' => 'Skyldig arbeidsgiveravgift', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],
            ['account_number' => '2780', 'name' => 'Påløpt arbeidsgiveravgift', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],
            ['account_number' => '2790', 'name' => 'Andre offentlige avgifter', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],
            ['account_number' => '2800', 'name' => 'Avsatt utbytte', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],
            ['account_number' => '2900', 'name' => 'Annen kortsiktig gjeld', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],
            ['account_number' => '2910', 'name' => 'Gjeld til ansatte', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],
            ['account_number' => '2920', 'name' => 'Gjeld til eiere', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],
            ['account_number' => '2960', 'name' => 'Påløpte kostnader', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],
            ['account_number' => '2970', 'name' => 'Forskuddsfakturert driftsinntekt', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],
            ['account_number' => '2990', 'name' => 'Annen kortsiktig gjeld', 'account_class' => '2', 'account_type' => 'liability', 'is_system' => true],

            // Klasse 3 - Salgsinntekter (Revenue)
            ['account_number' => '3000', 'name' => 'Salgsinntekt, avgiftspliktig', 'account_class' => '3', 'account_type' => 'revenue', 'is_system' => true, 'vat_code' => '3'],
            ['account_number' => '3100', 'name' => 'Salgsinntekt, avgiftsfri', 'account_class' => '3', 'account_type' => 'revenue', 'is_system' => true],
            ['account_number' => '3200', 'name' => 'Salgsinntekt, utenfor avgiftsområdet', 'account_class' => '3', 'account_type' => 'revenue', 'is_system' => true],
            ['account_number' => '3400', 'name' => 'Offentlig tilskudd/refusjon', 'account_class' => '3', 'account_type' => 'revenue', 'is_system' => true],
            ['account_number' => '3440', 'name' => 'Sykepenger refundert av NAV', 'account_class' => '3', 'account_type' => 'revenue', 'is_system' => true],
            ['account_number' => '3500', 'name' => 'Provisjonsinntekt', 'account_class' => '3', 'account_type' => 'revenue', 'is_system' => true],
            ['account_number' => '3600', 'name' => 'Leieinntekt', 'account_class' => '3', 'account_type' => 'revenue', 'is_system' => true],
            ['account_number' => '3700', 'name' => 'Gevinst ved avgang anleggsmidler', 'account_class' => '3', 'account_type' => 'revenue', 'is_system' => true],
            ['account_number' => '3800', 'name' => 'Rabatter og andre salgsinntektsreduksjon', 'account_class' => '3', 'account_type' => 'revenue', 'is_system' => true],
            ['account_number' => '3900', 'name' => 'Andre driftsinntekter', 'account_class' => '3', 'account_type' => 'revenue', 'is_system' => true],

            // Klasse 4 - Varekostnad (Cost of goods)
            ['account_number' => '4000', 'name' => 'Varekjøp', 'account_class' => '4', 'account_type' => 'expense', 'is_system' => true, 'vat_code' => '1'],
            ['account_number' => '4100', 'name' => 'Råvarer og halvfabrikat', 'account_class' => '4', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '4200', 'name' => 'Innkjøp av varer for videresalg', 'account_class' => '4', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '4300', 'name' => 'Innkjøp av tjenester', 'account_class' => '4', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '4400', 'name' => 'Fremmedytelse og underentreprise', 'account_class' => '4', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '4500', 'name' => 'Beholdningsendring', 'account_class' => '4', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '4600', 'name' => 'Frakt og forsikring ved varekjøp', 'account_class' => '4', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '4700', 'name' => 'Svinn', 'account_class' => '4', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '4800', 'name' => 'Rabatter og andre kjøpsprisreduksjon', 'account_class' => '4', 'account_type' => 'expense', 'is_system' => true],

            // Klasse 5 - Lønn og personal (Payroll)
            ['account_number' => '5000', 'name' => 'Lønn', 'account_class' => '5', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '5010', 'name' => 'Faste lønninger', 'account_class' => '5', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '5020', 'name' => 'Timelønninger', 'account_class' => '5', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '5030', 'name' => 'Overtid', 'account_class' => '5', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '5090', 'name' => 'Feriepenger', 'account_class' => '5', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '5100', 'name' => 'Godtgjørelse til styre og bedriftsforsamling', 'account_class' => '5', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '5200', 'name' => 'Fri bil', 'account_class' => '5', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '5210', 'name' => 'Fri telefon', 'account_class' => '5', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '5290', 'name' => 'Andre naturalytelser', 'account_class' => '5', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '5300', 'name' => 'Sykepenger', 'account_class' => '5', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '5400', 'name' => 'Arbeidsgiveravgift', 'account_class' => '5', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '5420', 'name' => 'Arbeidsgiveravgift av påløpne feriepenger', 'account_class' => '5', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '5500', 'name' => 'Andre personalkostnader', 'account_class' => '5', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '5600', 'name' => 'Arbeidsskadeforsikring', 'account_class' => '5', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '5700', 'name' => 'Refusjon av sykepenger', 'account_class' => '5', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '5800', 'name' => 'Refusjon av arbeidsgiveravgift', 'account_class' => '5', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '5900', 'name' => 'Annen personalkostnad', 'account_class' => '5', 'account_type' => 'expense', 'is_system' => true],

            // Klasse 6 - Avskrivninger (Depreciation)
            ['account_number' => '6000', 'name' => 'Avskrivning på bygninger og annen fast eiendom', 'account_class' => '6', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '6010', 'name' => 'Avskrivning på transportmidler', 'account_class' => '6', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '6015', 'name' => 'Avskrivning på maskiner og anlegg', 'account_class' => '6', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '6017', 'name' => 'Avskrivning på inventar', 'account_class' => '6', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '6020', 'name' => 'Avskrivning på immaterielle eiendeler', 'account_class' => '6', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '6050', 'name' => 'Nedskrivning anleggsmidler', 'account_class' => '6', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '6100', 'name' => 'Frakt og transport', 'account_class' => '6', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '6200', 'name' => 'Elektrisitet', 'account_class' => '6', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '6300', 'name' => 'Leie lokaler', 'account_class' => '6', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '6310', 'name' => 'Leie maskiner og inventar', 'account_class' => '6', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '6320', 'name' => 'Leie datautstyr', 'account_class' => '6', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '6340', 'name' => 'Lys og varme', 'account_class' => '6', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '6360', 'name' => 'Renhold', 'account_class' => '6', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '6400', 'name' => 'Leie av transportmidler', 'account_class' => '6', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '6500', 'name' => 'Verktøy, inventar under 15000 kr', 'account_class' => '6', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '6510', 'name' => 'Data/telekomutstyr under 15000 kr', 'account_class' => '6', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '6520', 'name' => 'Programvare, årlige lisenser', 'account_class' => '6', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '6540', 'name' => 'Inventar', 'account_class' => '6', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '6600', 'name' => 'Reparasjon og vedlikehold bygning', 'account_class' => '6', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '6620', 'name' => 'Reparasjon og vedlikehold utstyr', 'account_class' => '6', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '6700', 'name' => 'Revisjons- og regnskapshonorarer', 'account_class' => '6', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '6720', 'name' => 'Honorar for økonomisk og juridisk bistand', 'account_class' => '6', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '6790', 'name' => 'Annen fremmed tjeneste', 'account_class' => '6', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '6800', 'name' => 'Kontorrekvisita', 'account_class' => '6', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '6810', 'name' => 'Datakommunikasjon', 'account_class' => '6', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '6820', 'name' => 'Telefon', 'account_class' => '6', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '6840', 'name' => 'Aviser, tidsskrifter, bøker', 'account_class' => '6', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '6860', 'name' => 'Møter, kurs, oppdatering', 'account_class' => '6', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '6890', 'name' => 'Annen kontorkostnad', 'account_class' => '6', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '6900', 'name' => 'Telefon', 'account_class' => '6', 'account_type' => 'expense', 'is_system' => true],

            // Klasse 7 - Andre driftskostnader (Other operating expenses)
            ['account_number' => '7000', 'name' => 'Drivstoff biler', 'account_class' => '7', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '7020', 'name' => 'Vedlikehold biler', 'account_class' => '7', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '7040', 'name' => 'Forsikring og avgifter biler', 'account_class' => '7', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '7100', 'name' => 'Bilgodtgjørelse, oppgavepliktig', 'account_class' => '7', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '7130', 'name' => 'Reisekostnader, oppgavepliktig', 'account_class' => '7', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '7140', 'name' => 'Reisekostnader, ikke oppgavepliktig', 'account_class' => '7', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '7150', 'name' => 'Diettkostnader, oppgavepliktig', 'account_class' => '7', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '7160', 'name' => 'Diettkostnader, ikke oppgavepliktig', 'account_class' => '7', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '7200', 'name' => 'Provisjonskostnad', 'account_class' => '7', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '7300', 'name' => 'Salgskostnader', 'account_class' => '7', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '7320', 'name' => 'Reklame og annonser', 'account_class' => '7', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '7350', 'name' => 'Representasjon', 'account_class' => '7', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '7400', 'name' => 'Kontingenter', 'account_class' => '7', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '7410', 'name' => 'Gaver, fradragsberettiget', 'account_class' => '7', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '7420', 'name' => 'Gaver, ikke fradragsberettiget', 'account_class' => '7', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '7500', 'name' => 'Forsikring', 'account_class' => '7', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '7600', 'name' => 'Patent- og lisenskostnader', 'account_class' => '7', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '7700', 'name' => 'Bankgebyrer', 'account_class' => '7', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '7750', 'name' => 'Tap på fordringer', 'account_class' => '7', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '7770', 'name' => 'Tap ved avgang av anleggsmidler', 'account_class' => '7', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '7790', 'name' => 'Annen kostnad', 'account_class' => '7', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '7800', 'name' => 'Tap på aksjer', 'account_class' => '7', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '7830', 'name' => 'Tap på andre verdipapirer', 'account_class' => '7', 'account_type' => 'expense', 'is_system' => true],

            // Klasse 8 - Finansposter (Financial items)
            ['account_number' => '8000', 'name' => 'Renteinntekter', 'account_class' => '8', 'account_type' => 'revenue', 'is_system' => true],
            ['account_number' => '8020', 'name' => 'Renteinntekt fra foretak i samme konsern', 'account_class' => '8', 'account_type' => 'revenue', 'is_system' => true],
            ['account_number' => '8040', 'name' => 'Andre renteinntekter', 'account_class' => '8', 'account_type' => 'revenue', 'is_system' => true],
            ['account_number' => '8050', 'name' => 'Valutagevinst', 'account_class' => '8', 'account_type' => 'revenue', 'is_system' => true],
            ['account_number' => '8060', 'name' => 'Aksjeutbytte', 'account_class' => '8', 'account_type' => 'revenue', 'is_system' => true],
            ['account_number' => '8070', 'name' => 'Gevinst ved salg av aksjer', 'account_class' => '8', 'account_type' => 'revenue', 'is_system' => true],
            ['account_number' => '8080', 'name' => 'Andre finansinntekter', 'account_class' => '8', 'account_type' => 'revenue', 'is_system' => true],
            ['account_number' => '8100', 'name' => 'Rentekostnader', 'account_class' => '8', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '8110', 'name' => 'Rentekostnader til foretak i samme konsern', 'account_class' => '8', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '8120', 'name' => 'Andre rentekostnader', 'account_class' => '8', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '8130', 'name' => 'Valutatap', 'account_class' => '8', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '8140', 'name' => 'Nedskrivning andre finansielle omløpsmidler', 'account_class' => '8', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '8150', 'name' => 'Nedskrivning finansielle anleggsmidler', 'account_class' => '8', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '8170', 'name' => 'Tap ved salg av aksjer', 'account_class' => '8', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '8180', 'name' => 'Andre finanskostnader', 'account_class' => '8', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '8300', 'name' => 'Skattekostnad på ordinært resultat', 'account_class' => '8', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '8320', 'name' => 'Endring utsatt skatt', 'account_class' => '8', 'account_type' => 'expense', 'is_system' => true],
            ['account_number' => '8800', 'name' => 'Årsresultat', 'account_class' => '8', 'account_type' => 'equity', 'is_system' => true],
            ['account_number' => '8900', 'name' => 'Overføring til/fra fond', 'account_class' => '8', 'account_type' => 'equity', 'is_system' => true],
            ['account_number' => '8910', 'name' => 'Overføring til udekket tap', 'account_class' => '8', 'account_type' => 'equity', 'is_system' => true],
            ['account_number' => '8920', 'name' => 'Overføring til annen egenkapital', 'account_class' => '8', 'account_type' => 'equity', 'is_system' => true],
            ['account_number' => '8960', 'name' => 'Overføring til fond for vurderingsforskjeller', 'account_class' => '8', 'account_type' => 'equity', 'is_system' => true],
            ['account_number' => '8990', 'name' => 'Udekket tap', 'account_class' => '8', 'account_type' => 'equity', 'is_system' => true],
        ];

        foreach ($accounts as $account) {
            Account::firstOrCreate(
                ['account_number' => $account['account_number']],
                $account
            );
        }
    }
}
