<?php

namespace Database\Seeders;

use App\Models\VatCode;
use Illuminate\Database\Seeder;

class VatCodeSeeder extends Seeder
{
    public function run(): void
    {
        $vatCodes = [
            // Salg av varer og tjenester i Norge (Utgående MVA)
            [
                'code' => '3',
                'name' => 'Utgående mva høy sats',
                'description' => 'Salg av varer og tjenester med 25% mva',
                'category' => 'salg_norge',
                'direction' => 'output',
                'rate' => 25.00,
                'affects_base' => true,
                'affects_tax' => true,
                'sign' => 1,
                'sort_order' => 10,
            ],
            [
                'code' => '31',
                'name' => 'Utgående mva middels sats',
                'description' => 'Salg av næringsmidler med 15% mva',
                'category' => 'salg_norge',
                'direction' => 'output',
                'rate' => 15.00,
                'affects_base' => true,
                'affects_tax' => true,
                'sign' => 1,
                'sort_order' => 20,
            ],
            [
                'code' => '33',
                'name' => 'Utgående mva lav sats',
                'description' => 'Salg av persontransport, kino, etc. med 12% mva',
                'category' => 'salg_norge',
                'direction' => 'output',
                'rate' => 12.00,
                'affects_base' => true,
                'affects_tax' => true,
                'sign' => 1,
                'sort_order' => 30,
            ],
            [
                'code' => '5',
                'name' => 'Utgående mva null sats',
                'description' => 'Omsetning fritatt for mva (innenlands)',
                'category' => 'salg_norge',
                'direction' => 'output',
                'rate' => 0.00,
                'affects_base' => true,
                'affects_tax' => false,
                'sign' => 1,
                'sort_order' => 40,
            ],
            [
                'code' => '6',
                'name' => 'Omsetning utenfor mva-loven',
                'description' => 'Omsetning som faller utenfor merverdiavgiftsloven',
                'category' => 'salg_norge',
                'direction' => 'output',
                'rate' => null,
                'affects_base' => true,
                'affects_tax' => false,
                'sign' => 1,
                'sort_order' => 50,
            ],

            // Kjøp av varer og tjenester i Norge (Inngående MVA - fradrag)
            [
                'code' => '1',
                'name' => 'Inngående mva høy sats',
                'description' => 'Fradrag for kjøp av varer og tjenester med 25% mva',
                'category' => 'kjop_norge',
                'direction' => 'input',
                'rate' => 25.00,
                'affects_base' => false,
                'affects_tax' => true,
                'sign' => -1,
                'sort_order' => 100,
            ],
            [
                'code' => '11',
                'name' => 'Inngående mva middels sats',
                'description' => 'Fradrag for kjøp med 15% mva',
                'category' => 'kjop_norge',
                'direction' => 'input',
                'rate' => 15.00,
                'affects_base' => false,
                'affects_tax' => true,
                'sign' => -1,
                'sort_order' => 110,
            ],
            [
                'code' => '13',
                'name' => 'Inngående mva lav sats',
                'description' => 'Fradrag for kjøp med 12% mva',
                'category' => 'kjop_norge',
                'direction' => 'input',
                'rate' => 12.00,
                'affects_base' => false,
                'affects_tax' => true,
                'sign' => -1,
                'sort_order' => 120,
            ],

            // Kjøp av tjenester fra utlandet (Import)
            [
                'code' => '86',
                'name' => 'Tjenester kjøpt fra utlandet med fradrag for mva høy sats',
                'description' => 'Kjøp av tjenester fra utlandet - beregnet mva 25%',
                'category' => 'import',
                'direction' => 'output',
                'rate' => 25.00,
                'affects_base' => true,
                'affects_tax' => true,
                'sign' => 1,
                'sort_order' => 200,
            ],
            [
                'code' => '86_fradrag',
                'name' => 'Tjenester kjøpt fra utlandet med fradrag for mva høy sats',
                'description' => 'Fradrag for mva på tjenester kjøpt fra utlandet 25%',
                'category' => 'import',
                'direction' => 'input',
                'rate' => 25.00,
                'affects_base' => false,
                'affects_tax' => true,
                'sign' => -1,
                'sort_order' => 201,
            ],
            [
                'code' => '87',
                'name' => 'Tjenester kjøpt fra utlandet uten fradrag for mva høy sats',
                'description' => 'Kjøp av tjenester fra utlandet uten fradragsrett - beregnet mva 25%',
                'category' => 'import',
                'direction' => 'output',
                'rate' => 25.00,
                'affects_base' => true,
                'affects_tax' => true,
                'sign' => 1,
                'sort_order' => 210,
            ],
            [
                'code' => '88',
                'name' => 'Kjøp av klimakvoter og gull',
                'description' => 'Kjøp med omvendt avgiftsplikt - klimakvoter og gull',
                'category' => 'import',
                'direction' => 'output',
                'rate' => 25.00,
                'affects_base' => true,
                'affects_tax' => true,
                'sign' => 1,
                'sort_order' => 220,
            ],
            [
                'code' => '88_fradrag',
                'name' => 'Kjøp av klimakvoter og gull - fradrag',
                'description' => 'Fradrag for mva ved kjøp av klimakvoter og gull',
                'category' => 'import',
                'direction' => 'input',
                'rate' => 25.00,
                'affects_base' => false,
                'affects_tax' => true,
                'sign' => -1,
                'sort_order' => 221,
            ],

            // Utførsel (Eksport)
            [
                'code' => '52',
                'name' => 'Utførsel av varer og tjenester',
                'description' => 'Eksport - avgiftsfri omsetning',
                'category' => 'export',
                'direction' => 'output',
                'rate' => 0.00,
                'affects_base' => true,
                'affects_tax' => false,
                'sign' => 1,
                'sort_order' => 300,
            ],

            // Andre forhold
            [
                'code' => '81',
                'name' => 'Innførsel av varer med fradrag',
                'description' => 'Import av varer med fradragsrett',
                'category' => 'other',
                'direction' => 'output',
                'rate' => 25.00,
                'affects_base' => true,
                'affects_tax' => true,
                'sign' => 1,
                'sort_order' => 400,
            ],
            [
                'code' => '81_fradrag',
                'name' => 'Innførsel av varer med fradrag - fradrag',
                'description' => 'Fradrag for import av varer',
                'category' => 'other',
                'direction' => 'input',
                'rate' => 25.00,
                'affects_base' => false,
                'affects_tax' => true,
                'sign' => -1,
                'sort_order' => 401,
            ],
            [
                'code' => '82',
                'name' => 'Innførsel av varer uten fradrag',
                'description' => 'Import av varer uten fradragsrett',
                'category' => 'other',
                'direction' => 'output',
                'rate' => 25.00,
                'affects_base' => true,
                'affects_tax' => true,
                'sign' => 1,
                'sort_order' => 410,
            ],
            [
                'code' => '89',
                'name' => 'Fisk mv. kjøpt fra primærnæring',
                'description' => 'Kjøp av fisk med omvendt avgiftsplikt',
                'category' => 'other',
                'direction' => 'output',
                'rate' => 11.11,
                'affects_base' => true,
                'affects_tax' => true,
                'sign' => 1,
                'sort_order' => 420,
            ],
            [
                'code' => '91',
                'name' => 'Tap på fordringer',
                'description' => 'Justering for tap på fordringer',
                'category' => 'other',
                'direction' => 'input',
                'rate' => null,
                'affects_base' => false,
                'affects_tax' => true,
                'sign' => -1,
                'sort_order' => 500,
            ],
            [
                'code' => '92',
                'name' => 'Justering av inngående mva',
                'description' => 'Justeringer av tidligere fradragsført mva',
                'category' => 'other',
                'direction' => 'input',
                'rate' => null,
                'affects_base' => false,
                'affects_tax' => true,
                'sign' => -1,
                'sort_order' => 510,
            ],
        ];

        foreach ($vatCodes as $code) {
            VatCode::updateOrCreate(
                ['code' => $code['code']],
                $code
            );
        }
    }
}
