<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Str;

class Post extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'slug',
        'excerpt',
        'body',
        'featured_image',
        'post_category_id',
        'author_id',
        'is_published',
        'published_at',
        'meta_title',
        'meta_description',
        'views',
    ];

    protected function casts(): array
    {
        return [
            'is_published' => 'boolean',
            'published_at' => 'datetime',
            'views' => 'integer',
        ];
    }

    public function category(): BelongsTo
    {
        return $this->belongsTo(PostCategory::class, 'post_category_id');
    }

    public function author(): BelongsTo
    {
        return $this->belongsTo(User::class, 'author_id');
    }

    public function scopePublished($query)
    {
        return $query->where('is_published', true)
            ->where(function ($q) {
                $q->whereNull('published_at')
                    ->orWhere('published_at', '<=', now());
            });
    }

    public function scopeOrdered($query)
    {
        return $query->orderByDesc('published_at')->orderByDesc('created_at');
    }

    public function isPublished(): bool
    {
        return $this->is_published && ($this->published_at === null || $this->published_at->isPast());
    }

    public function incrementViews(): void
    {
        $this->increment('views');
    }

    /**
     * Sanitize the body HTML to prevent XSS.
     *
     * Allows only safe tags generated by the Tiptap editor
     * and strips dangerous attributes like event handlers.
     */
    public function setBodyAttribute(?string $value): void
    {
        $this->attributes['body'] = $value ? self::sanitizeHtml($value) : null;
    }

    private static function sanitizeHtml(string $html): string
    {
        $allowedTags = '<p><br><strong><b><em><i><u><s><del><mark><sup><sub>'
            .'<code><pre><h1><h2><h3><h4><h5><h6>'
            .'<blockquote><ul><ol><li><hr><div><span><a><img>';

        $html = strip_tags($html, $allowedTags);

        // Strip event handler attributes (onclick, onerror, etc.)
        $html = preg_replace('/\s+on\w+\s*=\s*"[^"]*"/i', '', $html);
        $html = preg_replace('/\s+on\w+\s*=\s*\'[^\']*\'/i', '', $html);
        $html = preg_replace('/\s+on\w+\s*=\s*[^\s>]*/i', '', $html);

        // Strip javascript: protocol in href and src attributes
        $html = preg_replace('/(<a\b[^>]*)\s+href\s*=\s*["\']?\s*javascript:[^"\'>\s]*/i', '$1', $html);
        $html = preg_replace('/(<img\b[^>]*)\s+src\s*=\s*["\']?\s*javascript:[^"\'>\s]*/i', '$1', $html);

        return $html;
    }

    public function getReadingTimeAttribute(): int
    {
        $words = str_word_count(strip_tags($this->body ?? ''));

        return max(1, (int) ceil($words / 200));
    }

    public function getExcerptOrTruncatedBodyAttribute(): string
    {
        if ($this->excerpt) {
            return $this->excerpt;
        }

        return Str::limit(strip_tags($this->body ?? ''), 160);
    }
}
