<?php

namespace App\Models\Traits;

trait SanitizesHtml
{
    /**
     * Sanitize HTML to prevent XSS.
     *
     * Allows only safe tags generated by the Tiptap editor
     * and strips dangerous attributes like event handlers.
     */
    protected static function sanitizeHtml(string $html): string
    {
        $allowedTags = '<p><br><strong><b><em><i><u><s><del><mark><sup><sub>'
            .'<code><pre><h1><h2><h3><h4><h5><h6>'
            .'<blockquote><ul><ol><li><hr><div><span><a><img>';

        $html = strip_tags($html, $allowedTags);

        // Strip event handler attributes (onclick, onerror, etc.)
        $html = preg_replace('/\s+on\w+\s*=\s*"[^"]*"/i', '', $html);
        $html = preg_replace('/\s+on\w+\s*=\s*\'[^\']*\'/i', '', $html);
        $html = preg_replace('/\s+on\w+\s*=\s*[^\s>]*/i', '', $html);

        // Strip javascript: protocol in href and src attributes
        $html = preg_replace('/(<a\b[^>]*)\s+href\s*=\s*["\']?\s*javascript:[^"\'>\s]*/i', '$1', $html);
        $html = preg_replace('/(<img\b[^>]*)\s+src\s*=\s*["\']?\s*javascript:[^"\'>\s]*/i', '$1', $html);

        return $html;
    }
}
